# Generated by Django 3.2.23 on 2023-11-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventDescription', models.TextField(max_length=100)),
                ('eventLocation', models.CharField(max_length=50)),
                ('eventCapacity', models.PositiveIntegerField()),
                ('eventDate', models.DateField()),
                ('eventPoster', models.ImageField(upload_to='eventposters/')),
                ('eventCost', models.PositiveIntegerField()),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
