# Generated by Django 4.2.7 on 2023-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_auto_20231117_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDescription',
            field=models.TextField(max_length=10000),
        ),
    ]
