# Generated by Django 4.2.7 on 2023-11-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_alter_event_eventdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('image', models.ImageField(upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('artist', models.CharField(max_length=100)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='schedule/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventApp.event')),
            ],
        ),
    ]
