# Generated by Django 4.2.7 on 2023-11-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0006_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='desc_1',
        ),
        migrations.RemoveField(
            model_name='award',
            name='desc_2',
        ),
        migrations.RemoveField(
            model_name='award',
            name='desc_3',
        ),
        migrations.RemoveField(
            model_name='award',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='award',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='award',
            name='title_3',
        ),
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
