# Generated by Django 4.2.7 on 2023-11-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0007_remove_award_desc_1_remove_award_desc_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='heading',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
