# Generated by Django 4.2.7 on 2023-11-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0008_award_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='heading',
        ),
    ]
