# Generated by Django 4.2.7 on 2023-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0010_ticketbooking_delete_day_alter_partner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('ticket_type', models.CharField(choices=[('early_bird', 'Early Bird'), ('standard', 'Standard')], max_length=20)),
                ('num_tickets', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TicketBooking',
        ),
    ]
