# Generated by Django 4.2.7 on 2023-11-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0011_ticket_delete_ticketbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='artist',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='heading',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
