# Generated by Django 4.2.7 on 2023-11-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0012_rename_artist_schedule_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='author1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='heading1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
