# Generated by Django 4.2.7 on 2023-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0013_schedule_author1_schedule_heading1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='author',
            new_name='AfternoonAuthor',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='heading',
            new_name='AfternoonHeading',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='author1',
            new_name='EveningAuthor',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='heading1',
            new_name='EveningHeading',
        ),
        migrations.AddField(
            model_name='schedule',
            name='MorningAuthor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='MorningHeading',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
