# Generated by Django 4.2.7 on 2023-11-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0014_rename_author_schedule_afternoonauthor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
