# Generated by Django 4.2.7 on 2023-11-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0015_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventCapacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventCost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventDescription',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventPoster',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
