# Generated by Django 4.2.7 on 2023-11-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0017_event_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timestamp',
        ),
    ]
